### ISSUE TITLE
Question about how to glue detection results on each frame

### ISSUE THREAD

**Issue by Picasso-Wang** [joslefaure/HIT#1]
Thank you for the wonderful work. I have read the paper and have some questions: How does your framework determine the start and end frame of an action in a video? Is a linking algorithm adopted to  link per-frame detections together?

**Comment by joslefaure** [comment]
Hi Peng,

Thanks for the reading our paper.
We use off-the-shelf bbox detectors during inference, therefore we do not
have to regress the bounding box coordinates.
To calculate frame mAP, we only consider individual frames and for video
mAP, we take the frames' average confidence score.

Does this answers your question?

**Comment by Picasso-Wang** [comment]
Hi, Thank you for the reply. Sorry that I had a little bit misunderstanding about your work when I open this issue. So I re-edited the question just now.
Thank you for your explain on the calculation method of frame mAP and video mAP. However, I still don't understand how the video mAP is calculated in your work.

**Comment by joslefaure** [comment]
Knowing the start and end of an action is not necessary for action detection frameworks (it is, however, for action recognition).
For instance, if we have four videos `(v1, v2, v3 and v4)` and two action `(a1 and a2)`, we only need the average score of each video with respect to each class. The video mAP calculator will need something like that: `a1: [(v1, v1_score, v1_bboxes ), (v2, v2_score, v2_bboxes)...]...`
If this is still confusing, please look at [YOWO](https://github.com/wei-tim/YOWO/blob/master/video_mAP.py) or [MultiSports](https://codalab.lisn.upsaclay.fr/competitions/3736#learn_the_details-submissions). We basically followed the MultiSports format and used the YOWO code as reference

**Comment by Picasso-Wang** [comment]
Thanks for your detailed reply. I will read the references you mentioned.

**Comment by joslefaure** [comment]
If you have further questions on the subject, feel free to reopen the issue. We are currently working on preparing the code for open-source, we will include the evaluation codes as well.
