### ISSUE TITLE
ModuleNotFoundError: No module named 'hit._custom_cuda_ext'

### ISSUE THREAD

**Issue by hongminglin08** [joslefaure/HIT#10]
when i meet this error ,i think there is something wrong with the path , but i just can not find the module '_custom_cuda_ext' in my project ,could you tell me how to fix this error?
![image](https://user-images.githubusercontent.com/52478955/218670526-80c38eb1-81b1-4be5-aa82-57f59b32565d.png)

**Comment by joslefaure** [comment]
I think this has to do with the module not successfully installed
