### ISSUE TITLE
the data of UCF101-24 

### ISSUE THREAD

**Issue by yan-ctrl** [joslefaure/HIT#11]
Hello, can you share the data of UCF101-24? I want to try the training of AVA dataset after UCF101-24 and JHMDB training. I hope you can share it with me. Thank you very much!

**Comment by yan-ctrl** [comment]
The AVA data set is too large. It takes a long time to train once

**Comment by joslefaure** [comment]
I used 8 32GB Titan GPUs to train it. It took around 25 hours

**Comment by yan-ctrl** [comment]
I don't have so many cards. The device is limited. The processing method of UCF101-24 is the same as that of JHMDB, right? Can you share with me what you still have?
