### ISSUE TITLE
get_ Keypoints？

### ISSUE THREAD

**Issue by yan-ctrl** [joslefaure/HIT#14]
Hello, I have a very confused question about your jhmdb.py's handling of JHMDB dataset tags. The experiment is very urgent. I hope to get your reply. In jhmdb.py, you define a function: get_ Keypoints (self, idx, im_w, im_h, orig_boxes), return kpts_ Boxes, which is the largest bboxes of the original real bbox iou, right? But I see your code boxes=BoxList (boxs_sensor, (im_w, im_h), mode="xywh"). convert ("xyxy"), while orig_ Boxes=boxes. bbox,Description orig_ Boxes was originally in the xywh format and needs to be converted to the xyxy format, but in get_ During keypoints processing, idx_ to_ Keep=np.argmax (iou (orig_boxes, boxes), 1), you directly calculated the iou value and returned the index. Boxes has not been converted to xyxy. I know it is my understanding problem, but I don't know what went wrong. Can you tell me?

**Comment by joslefaure** [comment]
Because the boxes retrieved by detectron are already in xyxy format

**Comment by yan-ctrl** [comment]
Thank you for your positive reply, but I still have questions, in https://github.com/joslefaure/HIT/blob/master/hit/dataset/datasets/jhmdb.py Of the 170 to 181 lines, 177 lines, your code is boxes=BoxList (boxs_sensor, (im_w, im_h), mode="xywh"). convert ("xyxy"), and then to 193 lines orig_ Boxes=boxes. bbox, here is the converted form. Convert xywh to xyxy, and I compared jhmdb_ train_ gt_ Min.json and jhmdb_ train_ person_ bbox_ The value of "bbox" in the same "image_id" in the two kpts.json files is similar. Should the GT value also be in the form of xyxy，No conversion?

**Comment by joslefaure** [comment]
Fixed in the last commit. 
It's nice that you have opened a new issue for this question. It's difficult to track the issues when the questions asked are unrelated to the original issue title

**Comment by yan-ctrl** [comment]
ok, thank you.
