### ISSUE TITLE
AssertionError: The shape of tensor class logits doesn't match total number of action classes.

### ISSUE THREAD

**Issue by hongminglin08** [joslefaure/HIT#18]
We have modified and run the code of AVA dataset, and the error appears as follows. May I ask how to solve it？
![image](https://github.com/joslefaure/HIT/assets/52478955/1dd9ab12-7861-49c5-8499-783ae81276e5)

**Comment by joslefaure** [comment]
AVA has 80 classes. Locate these lines in `hit/config/default.py` and modify them as follows:

```python
_C.MODEL.ROI_ACTION_HEAD.NUM_CLASSES = 80

# Action loss evaluator config.
_C.MODEL.ROI_ACTION_HEAD.PROPOSAL_PER_CLIP = 10
_C.MODEL.ROI_ACTION_HEAD.NUM_PERSON_MOVEMENT_CLASSES = 14
_C.MODEL.ROI_ACTION_HEAD.NUM_OBJECT_MANIPULATION_CLASSES = 49
_C.MODEL.ROI_ACTION_HEAD.NUM_PERSON_INTERACTION_CLASSES = 17
```

**Comment by hongminglin08** [comment]
> AVA has 80 classes. Locate these lines in `hit/config/default.py` and modify them as follows:
> 
> ```python
> _C.MODEL.ROI_ACTION_HEAD.NUM_CLASSES = 80
> 
> # Action loss evaluator config.
> _C.MODEL.ROI_ACTION_HEAD.PROPOSAL_PER_CLIP = 10
> _C.MODEL.ROI_ACTION_HEAD.NUM_PERSON_MOVEMENT_CLASSES = 14
> _C.MODEL.ROI_ACTION_HEAD.NUM_OBJECT_MANIPULATION_CLASSES = 49
> _C.MODEL.ROI_ACTION_HEAD.NUM_PERSON_INTERACTION_CLASSES = 17
> ```

**Comment by hongminglin08** [comment]
> AVA has 80 classes. Locate these lines in `hit/config/default.py` and modify them as follows:
> 
> ```python
> _C.MODEL.ROI_ACTION_HEAD.NUM_CLASSES = 80
> 
> # Action loss evaluator config.
> _C.MODEL.ROI_ACTION_HEAD.PROPOSAL_PER_CLIP = 10
> _C.MODEL.ROI_ACTION_HEAD.NUM_PERSON_MOVEMENT_CLASSES = 14
> _C.MODEL.ROI_ACTION_HEAD.NUM_OBJECT_MANIPULATION_CLASSES = 49
> _C.MODEL.ROI_ACTION_HEAD.NUM_PERSON_INTERACTION_CLASSES = 17
> ```

Thank you very much
