### ISSUE TITLE
AttributeError: 'numpy.ndarray' object has no attribute 'to'

### ISSUE THREAD

**Issue by hongminglin08** [joslefaure/HIT#21]
Is there anything keypoint needs to modify for ava data set? Why does the following error occur?
![image](https://github.com/joslefaure/HIT/assets/52478955/6abb880b-cdc1-491a-8e7a-8e0f626a71aa)

**Comment by joslefaure** [comment]
This error is self descriptive. The keypoints should be inside a pytorch tensor to support the method `to`
