### ISSUE TITLE
Broken model links

### ISSUE THREAD

**Issue by Tsunehiko** [joslefaure/HIT#23]
Thank you very much for your excellent work. It appears that the links for the SlowFast and JHMDB models in MODEL_ZOO.md are broken. The SlowFast may be the same as the one published in HIT_ava's MODEL_ZOO.md. Could you please fix the links? Thank you.

**Comment by joslefaure** [comment]
Thank you for noticing that. The links to the SlowFast models from `HIT_ava` still work (they should be the same). 
I haven't added the JHMDB pretrained model yet.

**Comment by Tsunehiko** [comment]
Thank you for your reply. I would like to try training with the SlowFast pretrained model that is available in HIT_ava.

**Comment by fengjingchehu** [comment]
I want to know if you still have the pre-trained model and JHMDB model?
