### ISSUE TITLE
Backward Error

### ISSUE THREAD

**Issue by Tsunehiko** [joslefaure/HIT#24]
I tried running `python train_net.py --config-file "config_files/hitnet.yaml"`, but I encountered the following error. Could you advise on how to resolve this? I installed PyTorch 1.10.0. Thank you.

`RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [8, 1024]], which is output 0 of ReluBackward0, is at version 1; expected version 0 instead. Hint: the backtrace further above shows the operation that failed to compute its gradient. The variable in question was changed in there or anywhere later. Good luck!`

**Comment by joslefaure** [comment]
The code was tested with torch 1.71

**Comment by Tsunehiko** [comment]
Thanks, I'll try it
