### ISSUE TITLE
Hello, Thanks for your work. And I want to know How to construct a long-term feature bank for your temporal interaction

### ISSUE THREAD

**Issue by ping-High** [joslefaure/HIT#3]

**Comment by joslefaure** [comment]
You can achieve this with some minor tweaks to our memory pool, saving the final HIT features (before the classifier) into the memory pool. However, what I would recommend is creating an empty dictionary with specific keys (`frame_id` for instance) and appending the HIT features (before the classifier) to it as the model converges.
