### ISSUE TITLE
python setup.py bdist_wheel did not run successfully.

### ISSUE THREAD

**Issue by bulkpanda** [joslefaure/HIT#30]
After I run 'pip install -e .' I get the following error.
cl : Command line error D8021 : invalid numeric argument '/Wno-cpp'
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2.
I looked at similar issues, for example one is here: https://github.com/cocodataset/cocoapi/issues/51.
I tried changing extra_compile_args variable to extra_compile_args={'gcc': ['/Qstd=c99']}.
I use windows 11.

**Comment by joslefaure** [comment]
I can't be sure about the behavior of this program on Windows, I haven't tried it
