### ISSUE TITLE
Calculate frame mAP

### ISSUE THREAD

**Issue by ZWXCV** [joslefaure/HIT#33]
Hello, author. May I know how to calculate frame mAP？Thank you very much.

**Comment by joslefaure** [comment]
The code includes both frame and video mAP calculations. We described how to calculate frame mAP in this section: https://github.com/joslefaure/HIT/blob/master/GETTING_STARTED.md#inference

**Comment by ZWXCV** [comment]
Thanks for the author's reply, I can indeed get videomAP through the instruction, but when I execute "python compute_video_map.py frameAP JHMDB-GT.pkl result_jhmdb.pkl" I will get a syntax error. The following is the error message:
Traceback (most recent call last):
  File "compute_video_map.py", line 427, in <module>
    frameAP(args.groundtruth, args.detections, args.thr)
  File "compute_video_map.py", line 86, in frameAP
    detections = alldets[alldets[:, 2] == ilabel, :]
TypeError: unhashable type: 'slice'
According to the error message TypeError: unhashable type: 'slice', the slicing operation cannot be applied to NumPy arrays.
Look forward to the author's answer，thank you very much.
