### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by fengjingchehu** [joslefaure/HIT#38]
ImportError:hit/_custom_cuda_ext.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN3c104cuda20getCurrentCUDAStreamEa
my torch   is  1.7.1+cu101

**Comment by joslefaure** [comment]
Try uninstalling and installing torch. And then install `hit`.

**Comment by fengjingchehu** [comment]
i successfully made it with pytorch 1.7.1   python 3.8 and cuda 10.1. And i wonder if i am able to get some visable results?
