### ISSUE TITLE
How to prepare dataset step by step

### ISSUE THREAD

**Issue by ccx2022** [joslefaure/HIT#4]
Thanks a lot ! Could you please tell us how to prepare other datasets ( UCF101、AVA) step by step ?

**Comment by joslefaure** [comment]
Since all these datasets are a bit different, it will take some time to arrange and publish the code (let's say 2-3 weeks)

**Comment by joslefaure** [comment]
I updated the data preparation step for AVA, it's far from exhaustive but should get you started. If there are any problem, feel free to reopen this issue or create a new one. I apologize for the long delay
