### ISSUE TITLE
J-HMDB Model link is not working

### ISSUE THREAD

**Issue by HaithemH** [joslefaure/HIT#40]
Link redirection to master branch!
Any other link to get the pretrained ?

**Comment by joslefaure** [comment]
A lot of people have pointed this out, and I apologize I haven't really looked into it. I will upload my latest checkpoint ASAP. Though training the model only takes around 4 hours

**Comment by joslefaure** [comment]
The link is updated: https://drive.google.com/file/d/1YwknoD4incjAJWQJajT8eRKqXmX0pqie/view?usp=sharing
