### ISSUE TITLE
“No such file or directory: 'data/jhmdb/annotations/jhmdb_train_gt_min.json'”

### ISSUE THREAD

**Issue by LIUHENGSHUAI** [joslefaure/HIT#52]
Hello, author. Sorry to bother you. When I run the train_net.py file, I encountered this error “No such file or directory: 'data/jhmdb/annotations/jhmdb_train_gt_min.json'”. Can you tell me where to find this JSON file?

"jhmdb_train_gt_min.json” and “jhmdb_test_gt_min.json“

**Comment by joslefaure** [comment]
Duplicated
