### ISSUE TITLE
map value in the AVA dataset；SlowFast-Resnet50

### ISSUE THREAD

**Issue by yan-ctrl** [joslefaure/HIT#9]
Hello, can you tell me what the map value in the AVA dataset is when SlowFast-Resnet50 is used as the backone?

**Comment by joslefaure** [comment]
I did not try SlowFast-Resnet50 on AVA but rather SlowFast-Resnet101. The
mAP is 32.6

**Comment by yan-ctrl** [comment]
Ok, thank you for your reply. For the data loader script of the AVA dataset, I have some difficulties in modifying it myself. You have told us how to prepare the AVA dataset. Can you tell me how to train the AVA dataset?

**Comment by joslefaure** [comment]
Given the large disparity between the datasets, I had to open another repo specifically for AVA, please find it there: https://github.com/joslefaure/HIT_ava. If you have any issue regarding AVA, please open them from the other repo. Thanks
